version: "3.9"
services:
  auth:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    ports:
      - "1433:1433"
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"