// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kwetter_authentication;

namespace kwetter_authentication.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210421120921_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kwetter_authentication.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "feabb8fb-6d8c-48a4-b060-e02c66b25405",
                            Avatar = "https://cdn.pixabay.com/photo/2018/08/28/12/41/avatar-3637425_1280.png",
                            Biography = "Zit hier voor de fun, voor de gezelligheid, voor de humor, beetje slap ouwehoeren, als ik gemekker wil koop ik wel een geit.",
                            Country = "NL",
                            Email = "aron@email.com",
                            Name = "Aron Heesakkers",
                            Password = "5.iSz3oLa2gaAw3sjTUjHG7A==.cXtCflhoIMH2+jka0xFhjHZenRDlgQW5UbiK4zxaOyo=",
                            Role = "ADMIN",
                            Username = "AronKwats"
                        },
                        new
                        {
                            Id = "c30fa353-d4e2-4b72-bbcf-0cd963763316",
                            Country = "NL",
                            Email = "jaap@email.com",
                            Name = "Jaap van der Meer",
                            Password = "5.iSz3oLa2gaAw3sjTUjHG7A==.cXtCflhoIMH2+jka0xFhjHZenRDlgQW5UbiK4zxaOyo=",
                            Role = "MODERATOR",
                            Username = "Jaapie98"
                        },
                        new
                        {
                            Id = "25853618-ef7b-44e8-aec2-bc7dae97498b",
                            Country = "NL",
                            Email = "sverre@email.com",
                            Name = "Sverre van Gompel",
                            Password = "5.iSz3oLa2gaAw3sjTUjHG7A==.cXtCflhoIMH2+jka0xFhjHZenRDlgQW5UbiK4zxaOyo=",
                            Role = "USER",
                            Username = "SverrieBoy"
                        },
                        new
                        {
                            Id = "61e1b100-6626-4aa0-b15b-53a1fe5503ec",
                            Country = "NL",
                            Email = "tim@email.com",
                            Name = "Tim la Haije",
                            Password = "5.iSz3oLa2gaAw3sjTUjHG7A==.cXtCflhoIMH2+jka0xFhjHZenRDlgQW5UbiK4zxaOyo=",
                            Role = "USER",
                            Username = "Timothy"
                        },
                        new
                        {
                            Id = "5685180c-a18e-4fc9-9d79-985f85b8fc1d",
                            Country = "NL",
                            Email = "dirk@email.com",
                            Name = "Dirk van de Waerden",
                            Password = "5.iSz3oLa2gaAw3sjTUjHG7A==.cXtCflhoIMH2+jka0xFhjHZenRDlgQW5UbiK4zxaOyo=",
                            Role = "USER",
                            Username = "Dirkvdw"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
